# Generated by Django 4.2.6 on 2023-10-10 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=255, verbose_name='Xona raqami')),
                ('floor', models.CharField(choices=[('1', '1 etaj'), ('2', '2 etaj'), ('3', '3 etaj'), ('4', '4 etaj')], max_length=255, verbose_name='Qavat')),
                ('room_type', models.CharField(choices=[('2', '2 kishilik'), ('3', '3 kishilik'), ('4', '4 kishilik')], max_length=255, verbose_name='Xona turi')),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.SH')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon raqami')),
                ('direction', models.CharField(blank=True, max_length=255, null=True, verbose_name="Yo'nalish")),
                ('faculty', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fakultet')),
                ('course', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kurs')),
                ('group', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guruh')),
                ('passport', models.CharField(blank=True, max_length=255, null=True, verbose_name='Passport')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Viloyat')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('diseases', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kasalliklar')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room', verbose_name='Xona')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
            },
        ),
    ]
