# Generated by Django 4.2.7 on 2024-01-27 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name="To'lov boshlanishi")),
                ('to_date', models.DateField(verbose_name="To'lov tugashi")),
                ('amount', models.IntegerField(verbose_name='Summa')),
                ('date', models.DateField(verbose_name="To'lov sanasi")),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatga olingan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
            },
        ),
    ]
